### ISSUE TITLE
Typo and inconsistency with documentation

### ISSUE THREAD

**Issue by OvOlzhas** [ydb-platform/benchbase#10]
https://github.com/ydb-platform/benchbase/blob/0706dd324940ee531d1bd337db2878b51aa19527/src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCBenchmark.java#L93

This if seems incorrect, since if `startWarehouseId` and `numwarehouses` are equal to 300, then 3000 terminals will be added on the first iteration of this cycle instead of 10. It would be more correct with the condition `w_id == numWarehouses + startWarehouseId - 1`.

---

https://github.com/ydb-platform/benchbase/blob/main/src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCBenchmark.java#L111

It seems that the TPC-C documentation does not imply the division of districts between terminals.

**Comment by eivanov89** [comment]
Nice catch, thank you!
